import Foundation
import SwiftUI

// MARK: - 界面语言
//
// 应用界面语言支持联合国六种官方语言：
//   阿拉伯语 (ar)、中文 (zh-Hans)、英语 (en)、法语 (fr)、俄语 (ru)、西班牙语 (es)
//
// 实现方式：纯 Swift 字典翻译表（不依赖 Xcode .xcstrings / .lproj 资源包，
// 因为本项目通过 swiftc / SPM 直接编译，资源捆绑不可靠）。

/// 应用支持的界面语言（联合国官方语言）。
enum AppLanguage: String, CaseIterable, Identifiable {

    case arabic = "ar"
    case chineseSimplified = "zh-Hans"
    case english = "en"
    case french = "fr"
    case russian = "ru"
    case spanish = "es"

    /// `Identifiable` conformance（直接把 rawValue 当作稳定 id）。
    var id: String { rawValue }

    /// 每种语言用「自身语言 + 英文备注」显示，方便用户识别。
    var localizedName: String {
        switch self {
        case .arabic:          return "العربية · Arabic"
        case .chineseSimplified: return "简体中文 · Chinese (Simplified)"
        case .english:         return "English"
        case .french:          return "Français · French"
        case .russian:         return "Русский · Russian"
        case .spanish:         return "Español · Spanish"
        }
    }

    /// 该语言对应的翻译表（key → 译文）。
    var translations: [String: String] {
        switch self {
        case .english:   return Self.tableEn
        case .chineseSimplified: return Self.tableZhHans
        case .french:    return Self.tableFr
        case .spanish:   return Self.tableEs
        case .russian:   return Self.tableRu
        case .arabic:    return Self.tableAr
        }
    }

    // MARK: - 英文（基准）

    fileprivate static let tableEn: [String: String] = [
        "app.name": "AI Chat",

        // 主窗口 / 消息区
        "no.chat.selected": "No Chat Selected",
        "no.chat.description": "Choose a chat from the sidebar or create a new one.",
        "chat.count": "%d chat(s)",
        "msgs.count": "%d msgs",
        "msg.count": "%d msg(s)",
        "you": "You",
        "assistant": "Assistant",
        "system": "System",
        "generating": "Generating…",
        "generating.waiting": "Waiting for response…",
        "attach.image": "Attach image(s)",
        "attach.pdf": "Attach PDF document",
        "attach.drop.hint": "Release to attach image / PDF",
        "pdf.pages": "%d page(s)",
        "pdf.mode.title": "How to send this PDF",
        "pdf.mode.images": "Send all pages as PNG",
        "pdf.mode.text": "Extract text and send",
        "pdf.mode.both": "Send both images and text",
        "pdf.mode.badge.images": "PNG",
        "pdf.mode.badge.text": "Text",
        "pdf.mode.badge.both": "All",
        "pdf.settings.title": "PDF Documents",
        "pdf.settings.maxPages": "Max pages to render (0 = all)",
        "pdf.settings.all": "All pages",
        "pdf.settings.count": "Max %d pages",
        "pdf.settings.hint": "Applies to “Send as PNG” and “Send both” modes. More pages = larger request, higher cost.",
        "agent.mode": "Agent",
        "agent.mode.help": "Enable built-in tool calling (web search, calculator)",
        "agent.tool.running": "🔧 Running tool %@…",
        "agent.tool.done": "✅ Tool %@ done, writing answer…",
        "sources.title": "Sources",
        "search.placeholder": "Search chats",
        "search.clear": "Clear search",
        "search.no.results": "No Results",
        "search.no.results.description": "Try a different keyword.",
        "custom.price": "Custom Price",
        "custom.price.enable": "Use custom price",
        "custom.price.input": "Input ($/1M tokens)",
        "custom.price.output": "Output ($/1M tokens)",
        "custom.price.cached": "Cached input ($/1M tokens)",
        "custom.price.cached.help": "Optional. Also shows the cost if the whole input prefix hits the prompt cache.",
        "custom.price.footer": "Overrides relay prices and the built-in price table.",
        "custom.price.badge": "custom price",
        "usage.cost.cached": "(if history hits cache ≈ %@)",
        "usage.cost.full": "Full price (no cache hits)",
        "usage.cost.cached.help": "Re-sent context billed at the cached-input rate; the newest message at the full input rate.",
        "usage.cache.hit": "cache hit %1$d%%",
        "cache.reset.profile": "Memory updated — this request's cache prefix was reset.",
        "cache.reset.history": "History edited — this request's cache prefix was reset from the edited point.",
        "tool.call.stripped": "Tool-call budget reached; the model produced no text reply.",
        "latex.on": "Compile LaTeX to PDF (Agent mode)",
        "latex.help": "Enabled. Local engines: %1$@",
        "latex.not.installed": "LaTeX is not installed on this Mac (MacTeX/TeX Live required).",
        "reasoning.title": "Thinking",
        "reasoning.chars": "%d chars",
        "reasoning.help": "Show the model's reasoning for this reply",
        "export.pdf": "Export as PDF",
        "export.pdf.failed": "Could not create the PDF.",
        "export.pdf.footer": "Exported from %1$@ · %2$@",
        "usage.tokens.real": "Last request (from the relay's real usage)",
        "usage.tokens.estimate": "Estimate for the next request (local token count)",
        "timestamp.warning": "When ON, the model gets the exact current time by calling a get_time tool. Cache-safe: tool results stay inside the request and are never persisted.",
        "detail.help": "Show generation details",
        "detail.title": "Message details",
        "detail.role": "Role",
        "detail.time": "Time",
        "detail.model": "Model",
        "detail.tokens": "Token usage",
        "detail.tokens.input": "Input",
        "detail.tokens.output": "Output",
        "detail.tokens.cache": "Cache (hit / miss)",
        "detail.tools": "Tools called",
        "detail.empty": "No generation metadata recorded (older message).",
        "usage.cache.detail": "Input tokens — hit %1$d, miss %2$d",
        "send": "Send (Enter)",
        "usage.tokens": "Tokens: ↑%1$@ ↓%2$@",
        "price.unknown": "(price unknown for this model)",
        "relay.price": "(relay price)",
        "msg.copy": "Copy",
        "codeblock.copied": "Copied",
        "msg.delete": "Delete",
        "msg.retry": "Retry",

        // 顶栏
        "profile": "Profile",
        "model": "Model",
        "stop": "Stop",
        "new.chat": "New Chat",
        "settings": "Settings",
        "no.profile.add": "No profile — add in Settings (⌘,)",
        "no.models.fetch": "No models — fetch in Settings",
        "new.chat.help": "Start a new chat (⌘N)",
        "settings.open.help": "Open API profile settings (⌘,)",

        // 侧边栏
        "delete.chat": "Delete Chat",
        "delete.all.chats": "Delete all chats",

        // 设置 - 列表
        "api.relay.profiles": "API Relay Profiles",
        "add.profile": "Add Profile",
        "no.profiles": "No Profiles",
        "no.profiles.description": "Add an OpenAI-compatible relay server to start chatting.",
        "user.profile": "User Profile",
        "user.profile.description": "Preferences the AI noticed from your chats. They're sent with the system prompt to personalize replies.",
        "no.preferences.learned": "No preferences learned yet. Mention what you like in a chat and the AI will remember it here.",
        "active": "Active",
        "fetch.models": "Fetch Models",
        "models.count": "%d models",
        "test": "Test",
        "edit": "Edit",
        "delete": "Delete",

        // 设置 - 编辑
        "add.profile.title": "Add Profile",
        "edit.profile.title": "Edit Profile",
        "profile.name": "Profile Name",
        "base.url": "Base URL",
        "api.key": "API Key",
        "generation": "Generation",
        "streaming.on": "Streaming render (token-by-token)",
        "timestamp.on": "Send timestamp (let the model know current time)",
        "generation.footer": "Render: Streaming → token-by-token; Non-streaming → show once when finished (both use SSE transport). Time-stamp: On → system prompt carries CURRENT TIME.",
        "system.prompt": "System Prompt",
        "system.prompt.hint": "System prompt is sent before each chat; told the model Markdown is rendered.",
        "system.prompt.footer": "Edit freely — e.g. set the assistant's role/persona.",
        "models": "Models",
        "selected.model": "Selected Model",
        "no.models.yet": "No models yet",
        "multimodal.hint": "🖼 = multimodal (vision) model",
        "fetch.models.button": "Fetch Models",
        "cancel": "Cancel",
        "kb.add": "Add Personalization Block",
        "kb.generate": "Generate Personalization Block",
        "kb.generate.action": "Generate",
        "kb.generate.message": "Name this block so the assistant can fetch it later (e.g. “account info”). Its content will be an AI-written summary of this conversation.",
        "kb.generate.failed": "Couldn’t generate the block. Please try again.",
        "kb.generating": "Generating…",
        "kb.generate.help": "Turn this collection chat into a named personalization block",
        "kb.name": "Block name",
        "kb.collecting": "Personalization collection — tell the assistant the facts you want saved.",
        "kb.title": "%d personalization block(s)",
        "save": "Save",
        "add": "Add",

        // 通用状态
        "unnamed.profile": "Unnamed profile",
        "no.base.url": "No base URL set",
        "no.api.key": "No API key set",
        "no.model.selected": "No model selected",
        "operation.failed": "Operation Failed",
        "success": "Success",
        "memory.added": "Memory added/updated",
        "memory.removed": "Memory removed",
        "no.active.profile": "No active API profile. Add one in Settings first.",
        "no.configs.tag": "No profile — add in Settings (⌘,)",
        "model.empty.tag": "No models — fetch in Settings",
        "language.settings": "Interface Language",
        "language.hint": "Switch the app UI language. Matches your system language by default.",
        "appearance.font": "Font Preset",
        "appearance.theme": "Theme",
        "theme.system": "System",
        "theme.claude": "Claude (Cream & Clay)",
        "appearance.fontsize": "Font Size",
        "appearance.sample": "Sample text — The quick brown fox jumps over the lazy dog. 中文示例：敏捷的棕色狐狸跳过了懒狗。",
        "appearance.description": "Applies to chat messages instantly. Choose serif, sans, or mono.",
        "appearance.serif": "Serif (衬线)",
        "appearance.sans": "Sans (无衬线)",
        "appearance.mono": "Mono (等宽)",
        "appearance.font.import": "Import Serif Font…",
        "appearance.font.remove": "Remove",
        "appearance.font.none": "No imported font (system NY + Songti)",
        "appearance.size.small": "Small",
        "appearance.size.medium": "Medium",
        "appearance.size.large": "Large",
        "appearance.size.xlarge": "Extra Large",
        "backup.title": "Backup & Restore",
        "backup.description": "Export all data (chats, API profiles, user profile, appearance, language) as a ZIP. Import it on another machine to restore everything.",
        "backup.export": "Export Backup…",
        "backup.import": "Import Backup…",
        "backup.exported": "Backup exported",
        "backup.imported": "Backup imported",
        "backup.export.failed": "Export failed",
        "backup.import.failed": "Import failed",
        "backup.export.choose_format": "Choose export format",
        "backup.import.choose_format": "Choose import format",
        "backup.format.zip": "ZIP archive (readable)",
        "backup.format.sqlite": "SQLite database"
    ]

    // MARK: - 简体中文

    fileprivate static let tableZhHans: [String: String] = [
        "app.name": "AI 聊天",

        "no.chat.selected": "未选择会话",
        "no.chat.description": "从侧边栏选择一个会话，或新建一个。",
        "chat.count": "%d 个会话",
        "msgs.count": "%d 条消息",
        "msg.count": "%d 条消息",
        "you": "你",
        "assistant": "助手",
        "system": "系统",
        "generating": "生成中…",
        "generating.waiting": "等待响应…",
        "attach.image": "附加图片",
        "attach.pdf": "附加 PDF 文档",
        "attach.drop.hint": "松手即可附加图片 / PDF",
        "pdf.pages": "%d 页",
        "pdf.mode.title": "选择发送方式",
        "pdf.mode.images": "全部转成 PNG 发送",
        "pdf.mode.text": "提取文字发送",
        "pdf.mode.both": "图片 + 文字都发送",
        "pdf.mode.badge.images": "PNG",
        "pdf.mode.badge.text": "文字",
        "pdf.mode.badge.both": "全部",
        "pdf.settings.title": "PDF 文档发送",
        "pdf.settings.maxPages": "最多渲染页数（0 = 全部页）",
        "pdf.settings.all": "全部页（每一页）",
        "pdf.settings.count": "最多 %d 页",
        "pdf.settings.hint": "仅对「转成 PNG 发送」与「图片 + 文字都发送」生效；页数越多，请求越大、费用越高。",
        "agent.mode": "Agent 模式",
        "agent.mode.help": "启用内置工具调用（联网搜索、计算器）",
        "agent.tool.running": "🔧 正在调用工具「%@」…",
        "agent.tool.done": "✅ 工具「%@」已完成，正在整理答案…",
        "sources.title": "来源",
        "search.placeholder": "搜索聊天记录",
        "search.clear": "清除搜索",
        "search.no.results": "未找到结果",
        "search.no.results.description": "换个关键词试试。",
        "custom.price": "自定义价格",
        "custom.price.enable": "使用自定义价格",
        "custom.price.input": "输入价格（$/百万 token）",
        "custom.price.output": "输出价格（$/百万 token）",
        "custom.price.cached": "缓存读取价格（$/百万 token）",
        "custom.price.cached.help": "可选。填写后，状态栏会额外显示「输入全部命中缓存」时的预估费用。",
        "custom.price.footer": "优先于中转站价格与内置价格表，适用于中转站未返回定价的情况。",
        "custom.price.badge": "自定义价格",
        "usage.cost.cached": "（若历史上下文命中缓存 ≈ %@）",
        "usage.cost.full": "全价（无缓存命中）",
        "usage.cost.cached.help": "重复发送的上下文按缓存读取价计费，最新消息按全价。",
        "usage.cache.hit": "缓存命中 %1$d%%",
        "cache.reset.profile": "记忆已更新——本次请求的缓存前缀已重置。",
        "cache.reset.history": "历史已修改——本次请求的缓存前缀已从修改点重置。",
        "tool.call.stripped": "工具调用预算已用尽，模型未生成文字回答。",
        "latex.on": "LaTeX 编译为 PDF（Agent 模式）",
        "latex.help": "已启用。本机引擎：%1$@",
        "latex.not.installed": "本机未安装 LaTeX（需要 MacTeX / TeX Live）。",
        "reasoning.title": "思考过程",
        "reasoning.chars": "%d 字",
        "reasoning.help": "查看模型生成这条回复时的推理过程",
        "export.pdf": "导出为 PDF",
        "export.pdf.failed": "PDF 生成失败。",
        "export.pdf.footer": "由 %1$@ 导出 · %2$@",
        "usage.tokens.real": "上次请求（API 返回的实际用量）",
        "usage.tokens.estimate": "下一次请求估算（本地计数）",
        "timestamp.warning": "开启后，模型通过 get_time 工具获取当前时间。工具结果仅在请求内部使用、不落盘，因此不影响缓存命中。",
        "detail.help": "查看生成详情",
        "detail.title": "消息详情",
        "detail.role": "角色",
        "detail.time": "时间",
        "detail.model": "模型",
        "detail.tokens": "Token 用量",
        "detail.tokens.input": "输入",
        "detail.tokens.output": "输出",
        "detail.tokens.cache": "缓存（命中 / 未命中）",
        "detail.tools": "调用的工具",
        "detail.empty": "暂无生成元数据（旧消息）。",
        "usage.cache.detail": "输入 tokens — 命中 %1$d，未命中 %2$d",
        "send": "发送 (回车)",
        "usage.tokens": "Tokens：↑%1$@ ↓%2$@",
        "price.unknown": "(该模型价格未知)",
        "relay.price": "(中转站价格)",
        "msg.copy": "复制",
        "codeblock.copied": "已复制",
        "msg.delete": "删除",
        "msg.retry": "重新生成",

        "profile": "配置",
        "model": "模型",
        "stop": "停止",
        "new.chat": "新建会话",
        "settings": "设置",
        "no.profile.add": "无配置 — 请在设置中添加 (⌘,)",
        "no.models.fetch": "无模型 — 请在设置中获取",
        "new.chat.help": "新建会话 (⌘N)",
        "settings.open.help": "打开 API 配置设置 (⌘,)",

        "delete.chat": "删除会话",
        "delete.all.chats": "删除全部会话",

        "api.relay.profiles": "API 中转站配置",
        "add.profile": "添加配置",
        "no.profiles": "暂无配置",
        "no.profiles.description": "添加一个 OpenAI 兼容的中转服务器即可开始聊天。",
        "user.profile": "用户画像",
        "user.profile.description": "AI 从聊天中学到的偏好，将随系统提示一起发送以个性化回复。",
        "no.preferences.learned": "尚未学习到偏好。在聊天中提及你的喜好，AI 会在这里记住它。",
        "active": "使用中",
        "fetch.models": "获取模型",
        "models.count": "%d 个模型",
        "test": "测试",
        "edit": "编辑",
        "delete": "删除",

        "add.profile.title": "添加配置",
        "edit.profile.title": "编辑配置",
        "profile.name": "配置名称",
        "base.url": "基础地址",
        "api.key": "API 密钥",
        "generation": "生成",
        "streaming.on": "流式渲染（逐字显示）",
        "timestamp.on": "发送时间戳（让模型感知当前时间）",
        "generation.footer": "渲染：流式 → 逐字显示；非流式 → 结束后一次性显示（两者都走 SSE 传输）。时间戳：开 → 系统提示附带 CURRENT TIME。",
        "system.prompt": "系统提示",
        "system.prompt.hint": "每次聊天前发送的系统提示；已告知模型应用会渲染 Markdown。",
        "system.prompt.footer": "可自由编辑——例如设置助手的角色/人格。",
        "models": "模型",
        "selected.model": "已选模型",
        "no.models.yet": "暂无模型",
        "multimodal.hint": "🖼 = 多模态（视觉）模型",
        "fetch.models.button": "获取模型",
        "cancel": "取消",
        "kb.add": "添加个性化块",
        "kb.generate": "生成个性化块",
        "kb.generate.action": "生成",
        "kb.generate.message": "给这个个性化块起个名字，方便以后让助手按名字读取（例如「账户信息」）。内容会由 AI 把本段对话总结成简洁的知识块。",
        "kb.generate.failed": "生成个性化块失败，请重试。",
        "kb.generating": "正在生成…",
        "kb.generate.help": "把本次采集对话保存为命名个性化块",
        "kb.name": "个性化块名称",
        "kb.collecting": "个性化块采集 — 把想保存的个人信息（账户、偏好、固定事实）告诉助手。",
        "kb.title": "个性化块（%d）",
        "save": "保存",
        "add": "添加",

        "unnamed.profile": "未命名配置",
        "no.base.url": "未设置基础地址",
        "no.api.key": "未设置 API 密钥",
        "no.model.selected": "未选择模型",
        "operation.failed": "操作失败",
        "success": "成功",
        "memory.added": "记忆已添加/更新",
        "memory.removed": "记忆已删除",
        "no.active.profile": "没有激活的 API 配置，请先在设置中添加。",
        "no.configs.tag": "无配置 — 请在设置中添加 (⌘,)",
        "model.empty.tag": "无模型 — 请在设置中获取",
        "language.settings": "界面语言",
        "language.hint": "切换应用界面语言，默认跟随系统语言。",
        "appearance.font": "字体预设",
        "appearance.theme": "主题",
        "theme.system": "跟随系统",
        "theme.claude": "Claude 米白橙",
        "appearance.fontsize": "字号",
        "appearance.sample": "示例文本 — 敏捷的棕色狐狸跳过了懒狗。The quick brown fox jumps over the lazy dog.",
        "appearance.description": "即时应用到聊天消息。可选择衬线、无衬线或等宽。",
        "appearance.serif": "衬线 (Serif)",
        "appearance.sans": "无衬线 (Sans)",
        "appearance.mono": "等宽 (Mono)",
        "appearance.font.import": "导入衬线字体…",
        "appearance.font.remove": "移除",
        "appearance.font.none": "未导入（系统 New York + 宋体）",
        "appearance.size.small": "小",
        "appearance.size.medium": "中",
        "appearance.size.large": "大",
        "appearance.size.xlarge": "特大",
        "backup.export.choose_format": "选择导出格式",
        "backup.import.choose_format": "选择导入格式",
        "backup.format.zip": "ZIP 压缩包（可读）",
        "backup.format.sqlite": "SQLite 数据库"
    ]

    // MARK: - 法语

    fileprivate static let tableFr: [String: String] = [
        "app.name": "IA Chat",

        "no.chat.selected": "Aucune discussion sélectionnée",
        "no.chat.description": "Choisissez une discussion dans la barre latérale ou créez-en une nouvelle.",
        "chat.count": "%d discussion(s)",
        "msgs.count": "%d msg(s)",
        "msg.count": "%d msg(s)",
        "you": "Vous",
        "assistant": "Assistant",
        "system": "Système",
        "generating": "Génération…",
        "attach.image": "Joindre des images",
        "attach.pdf": "Joindre un document PDF",
        "pdf.pages": "%d page(s)",
        "agent.mode": "Agent",
        "agent.mode.help": "Activer les outils intégrés (recherche web, calculatrice)",
        "agent.tool.running": "🔧 Outil en cours : %@…",
        "agent.tool.done": "✅ Outil %@ terminé, rédaction de la réponse…",
        "sources.title": "Sources",
        "search.placeholder": "Rechercher les conversations",
        "search.clear": "Effacer la recherche",
        "search.no.results": "Aucun résultat",
        "search.no.results.description": "Essayez un autre mot-clé.",
        "custom.price": "Prix personnalisé",
        "custom.price.enable": "Utiliser un prix personnalisé",
        "custom.price.input": "Entrée ($/1M tokens)",
        "custom.price.output": "Sortie ($/1M tokens)",
        "custom.price.cached": "Entrée en cache ($/1M tokens)",
        "custom.price.cached.help": "Optionnel. Affiche aussi le coût si tout le préfixe d'entrée vient du cache.",
        "custom.price.footer": "Remplace les prix du relais et le tableau intégré.",
        "custom.price.badge": "prix personnalisé",
        "usage.cost.cached": "(si historique en cache ≈ %@)",
        "usage.cost.full": "Prix complet (aucun cache)",
        "usage.cost.cached.help": "Le contexte renvoyé est facturé au tarif du cache ; le dernier message au tarif complet.",
        "usage.cache.hit": "cache %1$d%%",
        "cache.reset.profile": "Mémoire mise à jour — le préfixe de cache de cette requête a été réinitialisé.",
        "cache.reset.history": "Historique modifié — le préfixe de cache de cette requête a été réinitialisé à partir du point modifié.",
        "tool.call.stripped": "Budget d'appels d'outils atteint ; le modèle n'a pas produit de réponse textuelle.",
        "latex.on": "Compiler du LaTeX en PDF (mode Agent)",
        "latex.help": "Activé. Moteurs locaux : %1$@",
        "latex.not.installed": "LaTeX n'est pas installé sur ce Mac (MacTeX/TeX Live requis).",
        "reasoning.title": "Raisonnement",
        "reasoning.chars": "%d caractères",
        "reasoning.help": "Voir le raisonnement du modèle",
        "export.pdf": "Exporter en PDF",
        "export.pdf.failed": "Impossible de créer le PDF.",
        "export.pdf.footer": "Exporté depuis %1$@ · %2$@",
        "usage.tokens.real": "Dernière requête (usage réel du relais)",
        "usage.tokens.estimate": "Estimation pour la prochaine requête (comptage local)",
        "timestamp.warning": "Activé : le modèle obtient l'heure via l'outil get_time. Sans impact sur le cache (les résultats d'outil ne sont pas persistés).",
        "detail.help": "Voir les détails de génération",
        "detail.title": "Détails du message",
        "detail.role": "Rôle",
        "detail.time": "Heure",
        "detail.model": "Modèle",
        "detail.tokens": "Tokens utilisés",
        "detail.tokens.input": "Entrée",
        "detail.tokens.output": "Sortie",
        "detail.tokens.cache": "Cache (succès / échec)",
        "detail.tools": "Outils appelés",
        "detail.empty": "Aucune métadonnée de génération (ancien message).",
        "usage.cache.detail": "Entrée — cache %1$d, hors cache %2$d",
        "send": "Envoyer (Entrée)",
        "usage.tokens": "Tokens : ↑%1$@ ↓%2$@",
        "price.unknown": "(prix inconnu pour ce modèle)",
        "relay.price": "(prix du relais)",

        "profile": "Profil",
        "model": "Modèle",
        "stop": "Arrêter",
        "new.chat": "Nouvelle discussion",
        "settings": "Réglages",
        "no.profile.add": "Aucun profil — ajoutez-en un dans les réglages (⌘,)",
        "no.models.fetch": "Aucun modèle — récupérez-en dans les réglages",
        "new.chat.help": "Démarrer une nouvelle discussion (⌘N)",
        "settings.open.help": "Ouvrir les réglages des profils API (⌘,)",

        "delete.chat": "Supprimer la discussion",
        "delete.all.chats": "Supprimer toutes les discussions",

        "api.relay.profiles": "Profils de relais API",
        "add.profile": "Ajouter un profil",
        "no.profiles": "Aucun profil",
        "no.profiles.description": "Ajoutez un serveur relais compatible OpenAI pour commencer à discuter.",
        "user.profile": "Profil utilisateur",
        "user.profile.description": "Préférences remarquées par l'IA. Elles sont envoyées avec le prompt système pour personnaliser les réponses.",
        "no.preferences.learned": "Aucune préférence apprise. Mentionnez ce que vous aimez dans une discussion et l'IA s'en souviendra ici.",
        "active": "Actif",
        "fetch.models": "Récupérer les modèles",
        "models.count": "%d modèle(s)",
        "test": "Tester",
        "edit": "Modifier",
        "delete": "Supprimer",

        "add.profile.title": "Ajouter un profil",
        "edit.profile.title": "Modifier le profil",
        "profile.name": "Nom du profil",
        "base.url": "URL de base",
        "api.key": "Clé API",
        "generation": "Génération",
        "streaming.on": "Streaming (sortie au fil de l'eau)",
        "timestamp.on": "Envoyer l'horodatage (faire connaître l'heure au modèle)",
        "generation.footer": "Streaming : activé → mot à mot. Horodatage : activé → CURRENT TIME dans le prompt système.",
        "system.prompt": "Prompt système",
        "system.prompt.hint": "Envoyé avant chaque discussion ; informe le modèle que le Markdown est rendu.",
        "system.prompt.footer": "Modifiable librement — p. ex. définir le rôle/persona de l'assistant.",
        "models": "Modèles",
        "selected.model": "Modèle sélectionné",
        "no.models.yet": "Aucun modèle",
        "multimodal.hint": "🖼 = modèle multimodal (vision)",
        "fetch.models.button": "Récupérer les modèles",
        "cancel": "Annuler",
        "save": "Enregistrer",
        "add": "Ajouter",

        "unnamed.profile": "Profil sans nom",
        "no.base.url": "URL de base non définie",
        "no.api.key": "Clé API non définie",
        "no.model.selected": "Aucun modèle sélectionné",
        "operation.failed": "Échec de l'opération",
        "success": "Succès",
        "memory.added": "Mémoire ajoutée/mise à jour",
        "memory.removed": "Mémoire supprimée",
        "no.active.profile": "Aucun profil API actif. Ajoutez-en un dans les réglages d'abord.",
        "no.configs.tag": "Aucun profil — ajoutez-en dans les réglages (⌘,)",
        "model.empty.tag": "Aucun modèle — récupérez-en dans les réglages",
        "language.settings": "Langue de l'interface",
        "language.hint": "Change la langue de l'interface. Suit la langue du système par défaut.",
        "appearance.font": "Police",
        "appearance.theme": "Thème",
        "theme.system": "Système",
        "theme.claude": "Claude (crème & argile)",
        "appearance.fontsize": "Taille",
        "appearance.sample": "Exemple — Le renard brun rapide saute par-dessus le chien paresseux.",
        "appearance.description": "S'applique instantanément aux messages. Choisissez serif, sans ou mono.",
        "appearance.serif": "Serif",
        "appearance.sans": "Sans",
        "appearance.mono": "Mono",
        "appearance.size.small": "Petite",
        "appearance.size.medium": "Moyenne",
        "appearance.size.large": "Grande",
        "appearance.size.xlarge": "Extra large"
    ]

    // MARK: - 西班牙语

    fileprivate static let tableEs: [String: String] = [
        "app.name": "IA Chat",

        "no.chat.selected": "Sin conversación seleccionada",
        "no.chat.description": "Elija una conversación en la barra lateral o cree una nueva.",
        "chat.count": "%d conversación(es)",
        "msgs.count": "%d msgs",
        "msg.count": "%d msg(s)",
        "you": "Tú",
        "assistant": "Asistente",
        "system": "Sistema",
        "generating": "Generando…",
        "attach.image": "Adjuntar imagen(es)",
        "attach.pdf": "Adjuntar documento PDF",
        "pdf.pages": "%d página(s)",
        "agent.mode": "Agente",
        "agent.mode.help": "Habilitar herramientas integradas (búsqueda web, calculadora)",
        "agent.tool.running": "🔧 Ejecutando herramienta %@…",
        "agent.tool.done": "✅ Herramienta %@ completada, redactando respuesta…",
        "sources.title": "Fuentes",
        "search.placeholder": "Buscar chats",
        "search.clear": "Borrar búsqueda",
        "search.no.results": "Sin resultados",
        "search.no.results.description": "Prueba con otra palabra clave.",
        "custom.price": "Precio personalizado",
        "custom.price.enable": "Usar precio personalizado",
        "custom.price.input": "Entrada ($/1M tokens)",
        "custom.price.output": "Salida ($/1M tokens)",
        "custom.price.cached": "Entrada en caché ($/1M tokens)",
        "custom.price.cached.help": "Opcional. Muestra también el coste si toda la entrada viene de la caché.",
        "custom.price.footer": "Anula los precios del relay y la tabla integrada.",
        "custom.price.badge": "precio personalizado",
        "usage.cost.cached": "(si el historial está en caché ≈ %@)",
        "usage.cost.full": "Precio completo (sin caché)",
        "usage.cost.cached.help": "El contexto reenviado se factura a tarifa de caché; el último mensaje a tarifa completa.",
        "usage.cache.hit": "caché %1$d%%",
        "cache.reset.profile": "Memoria actualizada — se reinició el prefijo de caché de esta solicitud.",
        "cache.reset.history": "Historial editado — se reinició el prefijo de caché de esta solicitud desde el punto editado.",
        "tool.call.stripped": "Se alcanzó el límite de llamadas a herramientas; el modelo no produjo una respuesta de texto.",
        "latex.on": "Compilar LaTeX a PDF (modo agente)",
        "latex.help": "Activado. Motores locales: %1$@",
        "latex.not.installed": "LaTeX no está instalado en este Mac (requiere MacTeX/TeX Live).",
        "reasoning.title": "Razonamiento",
        "reasoning.chars": "%d caracteres",
        "reasoning.help": "Ver el razonamiento del modelo",
        "export.pdf": "Exportar como PDF",
        "export.pdf.failed": "No se pudo crear el PDF.",
        "export.pdf.footer": "Exportado desde %1$@ · %2$@",
        "usage.tokens.real": "Última solicitud (uso real del relay)",
        "usage.tokens.estimate": "Estimación para la próxima solicitud (conteo local)",
        "timestamp.warning": "Activado: el modelo obtiene la hora con la herramienta get_time. Sin impacto en caché (los resultados no se persisten).",
        "detail.help": "Ver detalles de generación",
        "detail.title": "Detalles del mensaje",
        "detail.role": "Rol",
        "detail.time": "Hora",
        "detail.model": "Modelo",
        "detail.tokens": "Tokens usados",
        "detail.tokens.input": "Entrada",
        "detail.tokens.output": "Salida",
        "detail.tokens.cache": "Caché (aciertos / fallos)",
        "detail.tools": "Herramientas llamadas",
        "detail.empty": "Sin metadatos de generación (mensaje antiguo).",
        "usage.cache.detail": "Entrada — caché %1$d, no caché %2$d",
        "send": "Enviar (Intro)",
        "usage.tokens": "Tokens: ↑%1$@ ↓%2$@",
        "price.unknown": "(precio desconocido para este modelo)",
        "relay.price": "(precio del relay)",

        "profile": "Perfil",
        "model": "Modelo",
        "stop": "Detener",
        "new.chat": "Nueva conversación",
        "settings": "Ajustes",
        "no.profile.add": "Sin perfil — añada uno en Ajustes (⌘,)",
        "no.models.fetch": "Sin modelos — obtenga en Ajustes",
        "new.chat.help": "Iniciar nueva conversación (⌘N)",
        "settings.open.help": "Abrir ajustes de perfiles API (⌘,)",

        "delete.chat": "Eliminar conversación",
        "delete.all.chats": "Eliminar todas las conversaciones",

        "api.relay.profiles": "Perfiles de relay API",
        "add.profile": "Añadir perfil",
        "no.profiles": "Sin perfiles",
        "no.profiles.description": "Añada un servidor relay compatible con OpenAI para empezar a chatear.",
        "user.profile": "Perfil de usuario",
        "user.profile.description": "Preferencias que la IA notó en sus chats. Se envían con el prompt del sistema para personalizar respuestas.",
        "no.preferences.learned": "Aún no se aprendieron preferencias. Mencione lo que le gusta en un chat y la IA lo recordará aquí.",
        "active": "Activo",
        "fetch.models": "Obtener modelos",
        "models.count": "%d modelo(s)",
        "test": "Probar",
        "edit": "Editar",
        "delete": "Eliminar",

        "add.profile.title": "Añadir perfil",
        "edit.profile.title": "Editar perfil",
        "profile.name": "Nombre del perfil",
        "base.url": "URL base",
        "api.key": "Clave API",
        "generation": "Generación",
        "streaming.on": "Streaming (salida en directo)",
        "timestamp.on": "Enviar marca de hora (que el modelo sepa la hora actual)",
        "generation.footer": "Streaming: activado → palabra por palabra. Marca de hora: activada → CURRENT TIME en el prompt del sistema.",
        "system.prompt": "Prompt del sistema",
        "system.prompt.hint": "Se envía antes de cada chat; informa al modelo de que Markdown se renderiza.",
        "system.prompt.footer": "Edite libremente — p. ej. defina el rol/persona del asistente.",
        "models": "Modelos",
        "selected.model": "Modelo seleccionado",
        "no.models.yet": "Aún sin modelos",
        "multimodal.hint": "🖼 = modelo multimodal (visión)",
        "fetch.models.button": "Obtener modelos",
        "cancel": "Cancelar",
        "save": "Guardar",
        "add": "Añadir",

        "unnamed.profile": "Perfil sin nombre",
        "no.base.url": "URL base no definida",
        "no.api.key": "Clave API no definida",
        "no.model.selected": "Ningún modelo seleccionado",
        "operation.failed": "Error de operación",
        "success": "Éxito",
        "memory.added": "Memoria añadida/actualizada",
        "memory.removed": "Memoria eliminada",
        "no.active.profile": "Sin perfil API activo. Añada uno en Ajustes primero.",
        "no.configs.tag": "Sin perfil — añada en Ajustes (⌘,)",
        "model.empty.tag": "Sin modelos — obtenga en Ajustes",
        "language.settings": "Idioma de la interfaz",
        "language.hint": "Cambia el idioma de la interfaz. Sigue el idioma del sistema por defecto.",
        "appearance.font": "Tipo de letra",
        "appearance.theme": "Tema",
        "theme.system": "Sistema",
        "theme.claude": "Claude (crema y arcilla)",
        "appearance.fontsize": "Tamaño",
        "appearance.sample": "Ejemplo — El rápido zorro marrón salta sobre el perro perezoso.",
        "appearance.description": "Se aplica al instante a los mensajes. Elija serif, sans o mono.",
        "appearance.serif": "Serif",
        "appearance.sans": "Sans",
        "appearance.mono": "Mono",
        "appearance.size.small": "Pequeño",
        "appearance.size.medium": "Medio",
        "appearance.size.large": "Grande",
        "appearance.size.xlarge": "Extra grande"
    ]

    // MARK: - 俄语

    fileprivate static let tableRu: [String: String] = [
        "app.name": "ИИ-чат",

        "no.chat.selected": "Чат не выбран",
        "no.chat.description": "Выберите чат на боковой панели или создайте новый.",
        "chat.count": "%d чат(ов)",
        "msgs.count": "%d сообщ.",
        "msg.count": "%d сообщ.",
        "you": "Вы",
        "assistant": "Ассистент",
        "system": "Система",
        "generating": "Генерация…",
        "attach.image": "Прикрепить изображения",
        "attach.pdf": "Прикрепить PDF-документ",
        "pdf.pages": "%d стр.",
        "agent.mode": "Агент",
        "agent.mode.help": "Включить встроенные инструменты (поиск в интернете, калькулятор)",
        "agent.tool.running": "🔧 Инструмент %@ выполняется…",
        "agent.tool.done": "✅ Инструмент %@ выполнен, готовлю ответ…",
        "sources.title": "Источники",
        "search.placeholder": "Поиск по чатам",
        "search.clear": "Очистить поиск",
        "search.no.results": "Ничего не найдено",
        "search.no.results.description": "Попробуйте другой запрос.",
        "custom.price": "Своя цена",
        "custom.price.enable": "Использовать свою цену",
        "custom.price.input": "Ввод ($/1M токенов)",
        "custom.price.output": "Вывод ($/1M токенов)",
        "custom.price.cached": "Кэшированный ввод ($/1M токенов)",
        "custom.price.cached.help": "Необязательно. Показывает также стоимость, если весь ввод попадёт в кэш.",
        "custom.price.footer": "Имеет приоритет над ценами релея и встроенной таблицей.",
        "custom.price.badge": "своя цена",
        "usage.cost.cached": "(если история в кэше ≈ %@)",
        "usage.cost.full": "Полная цена (без кэша)",
        "usage.cost.cached.help": "Повторно отправляемый контекст по цене кэша, новое сообщение по полной цене.",
        "usage.cache.hit": "кэш %1$d%%",
        "cache.reset.profile": "Память обновлена — префикс кэша этого запроса был сброшен.",
        "cache.reset.history": "История изменена — префикс кэша этого запроса сброшен с изменённой точки.",
        "tool.call.stripped": "Достигнут лимит вызовов инструментов; модель не дала текстового ответа.",
        "latex.on": "Компиляция LaTeX в PDF (режим агента)",
        "latex.help": "Включено. Локальные движки: %1$@",
        "latex.not.installed": "LaTeX не установлен на этом Mac (нужен MacTeX/TeX Live).",
        "reasoning.title": "Рассуждения",
        "reasoning.chars": "%d симв.",
        "reasoning.help": "Показать рассуждения модели",
        "export.pdf": "Экспорт в PDF",
        "export.pdf.failed": "Не удалось создать PDF.",
        "export.pdf.footer": "Экспортировано из %1$@ · %2$@",
        "usage.tokens.real": "Последний запрос (реальный расход)",
        "usage.tokens.estimate": "Оценка для следующего запроса (локальный подсчёт)",
        "timestamp.warning": "Вкл.: модель получает время через инструмент get_time. Кэш не страдает (результаты не сохраняются).",
        "detail.help": "Показать детали генерации",
        "detail.title": "Детали сообщения",
        "detail.role": "Роль",
        "detail.time": "Время",
        "detail.model": "Модель",
        "detail.tokens": "Токены",
        "detail.tokens.input": "Вход",
        "detail.tokens.output": "Выход",
        "detail.tokens.cache": "Кэш (попадание / промах)",
        "detail.tools": "Вызванные инструменты",
        "detail.empty": "Нет метаданных генерации (старое сообщение).",
        "usage.cache.detail": "Ввод — кэш %1$d, промах %2$d",
        "send": "Отправить (Enter)",
        "usage.tokens": "Токены: ↑%1$@ ↓%2$@",
        "price.unknown": "(цена для этой модели неизвестна)",
        "relay.price": "(цена релея)",

        "profile": "Профиль",
        "model": "Модель",
        "stop": "Стоп",
        "new.chat": "Новый чат",
        "settings": "Настройки",
        "no.profile.add": "Нет профиля — добавьте в настройках (⌘,)",
        "no.models.fetch": "Нет моделей — получите в настройках",
        "new.chat.help": "Начать новый чат (⌘N)",
        "settings.open.help": "Открыть настройки профилей API (⌘,)",

        "delete.chat": "Удалить чат",
        "delete.all.chats": "Удалить все чаты",

        "api.relay.profiles": "Профили релеев API",
        "add.profile": "Добавить профиль",
        "no.profiles": "Нет профилей",
        "no.profiles.description": "Добавьте OpenAI-совместимый сервер-релей, чтобы начать общение.",
        "user.profile": "Профиль пользователя",
        "user.profile.description": "Предпочтения, замеченные ИИ в чатах. Они отправляются с системным промптом для персонализации ответов.",
        "no.preferences.learned": "Предпочтения ещё не изучены. Упомяните, что вам нравится, и ИИ запомнит это здесь.",
        "active": "Активен",
        "fetch.models": "Получить модели",
        "models.count": "%d модел(ей)",
        "test": "Тест",
        "edit": "Изменить",
        "delete": "Удалить",

        "add.profile.title": "Добавить профиль",
        "edit.profile.title": "Изменить профиль",
        "profile.name": "Имя профиля",
        "base.url": "Базовый URL",
        "api.key": "Ключ API",
        "generation": "Генерация",
        "streaming.on": "Стриминг (потоковый вывод)",
        "timestamp.on": "Отправлять метку времени (сообщить модели текущее время)",
        "generation.footer": "Стриминг: вкл → по токенам. Метка времени: вкл → CURRENT TIME в системном промпте.",
        "system.prompt": "Системный промпт",
        "system.prompt.hint": "Отправляется перед каждым чатом; сообщает модели, что Markdown рендерится.",
        "system.prompt.footer": "Можно редактировать — например, задать роль/персону ассистента.",
        "models": "Модели",
        "selected.model": "Выбранная модель",
        "no.models.yet": "Моделей пока нет",
        "multimodal.hint": "🖼 = мультимодальная (зрительная) модель",
        "fetch.models.button": "Получить модели",
        "cancel": "Отмена",
        "save": "Сохранить",
        "add": "Добавить",

        "unnamed.profile": "Безымянный профиль",
        "no.base.url": "Базовый URL не задан",
        "no.api.key": "Ключ API не задан",
        "no.model.selected": "Модель не выбрана",
        "operation.failed": "Ошибка операции",
        "success": "Успех",
        "memory.added": "Память добавлена/обновлена",
        "memory.removed": "Память удалена",
        "no.active.profile": "Нет активного профиля API. Сначала добавьте его в настройках.",
        "no.configs.tag": "Нет профиля — добавьте в настройках (⌘,)",
        "model.empty.tag": "Нет моделей — получите в настройках",
        "language.settings": "Язык интерфейса",
        "language.hint": "Переключить язык интерфейса. По умолчанию соответствует языку системы.",
        "appearance.font": "Шрифт",
        "appearance.theme": "Тема",
        "theme.system": "Система",
        "theme.claude": "Claude (крем и глина)",
        "appearance.fontsize": "Размер",
        "appearance.sample": "Пример — Быстрая коричневая лиса прыгает через ленивую собаку.",
        "appearance.description": "Применяется к сообщениям мгновенно. Выберите serif, sans или mono.",
        "appearance.serif": "Serif",
        "appearance.sans": "Sans",
        "appearance.mono": "Mono",
        "appearance.size.small": "Мелкий",
        "appearance.size.medium": "Средний",
        "appearance.size.large": "Крупный",
        "appearance.size.xlarge": "Очень крупный"
    ]

    // MARK: - 阿拉伯语

    fileprivate static let tableAr: [String: String] = [
        "app.name": "الدردشة الذكية",

        "no.chat.selected": "لم يتم تحديد محادثة",
        "no.chat.description": "اختر محادثة من الشريط الجانبي أو أنشئ محادثة جديدة.",
        "chat.count": "%d محادثة",
        "msgs.count": "%d رسالة",
        "msg.count": "%d رسالة",
        "you": "أنت",
        "assistant": "المساعد",
        "system": "النظام",
        "generating": "جارٍ التوليد…",
        "attach.image": "إرفاق صورة",
        "attach.pdf": "إرفاق مستند PDF",
        "pdf.pages": "%d صفحة",
        "agent.mode": "وكيل",
        "agent.mode.help": "تفعيل الأدوات المدمجة (بحث الويب، الآلة الحاسبة)",
        "agent.tool.running": "🔧 جارٍ تشغيل الأداة %@…",
        "agent.tool.done": "✅ اكتملت الأداة %@، جارٍ كتابة الإجابة…",
        "sources.title": "المصادر",
        "search.placeholder": "ابحث في المحادثات",
        "search.clear": "مسح البحث",
        "search.no.results": "لا توجد نتائج",
        "search.no.results.description": "جرّب كلمة مفتاحية مختلفة.",
        "custom.price": "سعر مخصص",
        "custom.price.enable": "استخدام سعر مخصص",
        "custom.price.input": "الإدخال ($/مليون رمز)",
        "custom.price.output": "الإخراج ($/مليون رمز)",
        "custom.price.cached": "الإدخال المخزّن ($/مليون رمز)",
        "custom.price.cached.help": "اختياري. يعرض أيضاً التكلفة إذا جاء الإدخال من ذاكرة التخزين المؤقت.",
        "custom.price.footer": "يتجاوز أسعار الخادم والجدول المدمج.",
        "custom.price.badge": "سعر مخصص",
        "usage.cost.cached": "(إذا كان السجل في الذاكرة ≈ %@)",
        "usage.cost.full": "السعر الكامل (بدون ذاكرة)",
        "usage.cost.cached.help": "يُحسب السياق المُعاد إرساله بسعر الذاكرة المؤقتة، والرسالة الأحدث بالسعر الكامل.",
        "usage.cache.hit": "الذاكرة المؤقتة %1$d%%",
        "cache.reset.profile": "تم تحديث الذاكرة — تمت إعادة تعيين بادئة التخزين المؤقت لهذا الطلب.",
        "cache.reset.history": "تم تعديل السجل — تمت إعادة تعيين بادئة التخزين المؤقت لهذا الطلب من النقطة المعدلة.",
        "tool.call.stripped": "تم الوصول إلى حد استدعاءات الأدوات؛ لم ينتج النموذج ردًا نصيًا.",
        "latex.on": "ترجمة LaTeX إلى PDF (وضع الوكيل)",
        "latex.help": "ممكّن. المحركات المحلية: %1$@",
        "latex.not.installed": "LaTeX غير مثبت على هذا الجهاز (يتطلب MacTeX/TeX Live).",
        "reasoning.title": "التفكير",
        "reasoning.chars": "%d حرف",
        "reasoning.help": "عرض تفكير النموذج",
        "export.pdf": "تصدير كـ PDF",
        "export.pdf.failed": "تعذّر إنشاء ملف PDF.",
        "export.pdf.footer": "تم التصدير من %1$@ · %2$@",
        "usage.tokens.real": "آخر طلب (الاستخدام الفعلي)",
        "usage.tokens.estimate": "تقدير للطلب التالي (عدد محلي)",
        "timestamp.warning": "عند التشغيل، يحصل النموذج على الوقت عبر أداة get_time. لا يؤثر على الذاكرة المؤقتة.",
        "detail.help": "عرض تفاصيل التوليد",
        "detail.title": "تفاصيل الرسالة",
        "detail.role": "الدور",
        "detail.time": "الوقت",
        "detail.model": "النموذج",
        "detail.tokens": "الرموز",
        "detail.tokens.input": "الإدخال",
        "detail.tokens.output": "الإخراج",
        "detail.tokens.cache": "الذاكرة المؤقتة (مخزّن / غير مخزّن)",
        "detail.tools": "الأدوات المستدعاة",
        "detail.empty": "لا توجد بيانات توليد (رسالة قديمة).",
        "usage.cache.detail": "الإدخال — مخزّن %1$d، غير مخزّن %2$d",
        "send": "إرسال (Enter)",
        "usage.tokens": "الرموز: ↑%1$@ ↓%2$@",
        "price.unknown": "(سعر هذا النموذج غير معروف)",
        "relay.price": "(سعر الوسيط)",

        "profile": "الملف",
        "model": "النموذج",
        "stop": "إيقاف",
        "new.chat": "محادثة جديدة",
        "settings": "الإعدادات",
        "no.profile.add": "لا يوجد ملف — أضفه في الإعدادات (⌘,)",
        "no.models.fetch": "لا توجد نماذج — اجلبها من الإعدادات",
        "new.chat.help": "بدء محادثة جديدة (⌘N)",
        "settings.open.help": "فتح إعدادات ملفات API (⌘,)",

        "delete.chat": "حذف المحادثة",
        "delete.all.chats": "حذف كل المحادثات",

        "api.relay.profiles": "ملفات وسائط API",
        "add.profile": "إضافة ملف",
        "no.profiles": "لا توجد ملفات",
        "no.profiles.description": "أضف خادم وسيط متوافقًا مع OpenAI لبدء الدردشة.",
        "user.profile": "ملف المستخدم",
        "user.profile.description": "تفضيلات لاحظها الذكاء الاصطناعي في محادثاتك. تُرسل مع موجه النظام لتخصيص الردود.",
        "no.preferences.learned": "لم تُتعلم تفضيلات بعد. اذكر ما يعجبك في محادثة وسيتذكرها الذكاء الاصطناعي هنا.",
        "active": "نشط",
        "fetch.models": "جلب النماذج",
        "models.count": "%d نموذج",
        "test": "اختبار",
        "edit": "تعديل",
        "delete": "حذف",

        "add.profile.title": "إضافة ملف",
        "edit.profile.title": "تعديل الملف",
        "profile.name": "اسم الملف",
        "base.url": "عنوان URL الأساسي",
        "api.key": "مفتاح API",
        "generation": "التوليد",
        "streaming.on": "البث (إخراج متدفق)",
        "timestamp.on": "إرسال الطابع الزمني (إعلام النموذج بالوقت الحالي)",
        "generation.footer": "البث: تشغيل → كلمة بكلمة. الطابع الزمني: تشغيل → CURRENT TIME في موجه النظام.",
        "system.prompt": "موجه النظام",
        "system.prompt.hint": "يُرسل قبل كل محادثة؛ يُعلم النموذج أن Markdown يُعرض.",
        "system.prompt.footer": "حرر بحرية — مثلًا اضبط دور/شخصية المساعد.",
        "models": "النماذج",
        "selected.model": "النموذج المحدد",
        "no.models.yet": "لا توجد نماذج بعد",
        "multimodal.hint": "🖼 = نموذج متعدد الوسائط (رؤية)",
        "fetch.models.button": "جلب النماذج",
        "cancel": "إلغاء",
        "save": "حفظ",
        "add": "إضافة",

        "unnamed.profile": "ملف بدون اسم",
        "no.base.url": "عنوان URL الأساسي غير مضبوط",
        "no.api.key": "مفتاح API غير مضبوط",
        "no.model.selected": "لم يُحدد نموذج",
        "operation.failed": "فشلت العملية",
        "success": "نجاح",
        "memory.added": "تمت إضافة/تحديث الذاكرة",
        "memory.removed": "تم حذف الذاكرة",
        "no.active.profile": "لا يوجد ملف API نشط. أضف واحدًا في الإعدادات أولًا.",
        "no.configs.tag": "لا يوجد ملف — أضفه في الإعدادات (⌘,)",
        "model.empty.tag": "لا توجد نماذج — اجلبها من الإعدادات",
        "language.settings": "لغة الواجهة",
        "language.hint": "بدّل لغة واجهة التطبيق. يتبع لغة النظام افتراضيًا.",
        "appearance.font": "الخط",
        "appearance.theme": "المظهر",
        "theme.system": "النظام",
        "theme.claude": "كلود (كريم وطين)",
        "appearance.fontsize": "الحجم",
        "appearance.sample": "مثال — الثعلب البني السريع يقفز فوق الكلب الكسول.",
        "appearance.description": "يُطبق على الرسائل فورًا. اختر serif أو sans أو mono.",
        "appearance.serif": "Serif",
        "appearance.sans": "Sans",
        "appearance.mono": "Mono",
        "appearance.size.small": "صغير",
        "appearance.size.medium": "متوسط",
        "appearance.size.large": "كبير",
        "appearance.size.xlarge": "كبير جدًا"
    ]
}

// MARK: - 本地化管理器

/// 界面本地化管理器：持有当前语言并负责查询翻译。
///
/// - 界面通过 `@EnvironmentObject` 观察，切换语言即时刷新。
/// - ViewModel / Service 可直接调用全局 `L("key")`。
final class LocalizationManager: ObservableObject {

    /// 全局共享实例（AppMain 会注入到 environment）。
    static let shared = LocalizationManager()

    /// `UserDefaults` 存储键。
    private static let languageKey = "appLanguage"

    /// 当前界面语言。
    @Published var current: AppLanguage {
        didSet {
            UserDefaults.standard.set(current.rawValue, forKey: Self.languageKey)
            UserDefaults.standard.synchronize()
        }
    }

    /// 持久化已保存的语言（默认跟随系统：中文则 zh-Hans，否则英文）。
    private init() {
        let stored = UserDefaults.standard.string(forKey: Self.languageKey)
        if let stored, let lang = AppLanguage(rawValue: stored) {
            current = lang
        } else {
            // 跟随系统语言：App 支持集内最接近系统的语言。
            let systemLang = Locale.preferredLanguages.first ?? "en"
            if systemLang.hasPrefix("zh") {
                current = .chineseSimplified
            } else if systemLang.hasPrefix("ar") {
                current = .arabic
            } else if systemLang.hasPrefix("fr") {
                current = .french
            } else if systemLang.hasPrefix("ru") {
                current = .russian
            } else if systemLang.hasPrefix("es") {
                current = .spanish
            } else {
                current = .english
            }
        }
    }

    /// 查询当前语言的翻译；缺失的 key 回退到英文。
    func tr(_ key: String) -> String {
        translations[key] ?? Self.englishFallback[key] ?? key
    }

    /// 带格式化参数的查询（`%d` / `%@`）。
    func tr(_ key: String, _ args: CVarArg...) -> String {
        String(format: tr(key), locale: Locale(identifier: current.rawValue), arguments: args)
    }

    /// 当前语言的翻译表（英文兜底）。
    private var translations: [String: String] {
        var table = AppLanguage.tableEn
        table.merge(current.translations) { _, localized in localized }
        return table
    }

    private static let englishFallback = AppLanguage.tableEn
}

// MARK: - 便捷全局函数

/// 界面文本快捷方式（任何层都可用）。
func L(_ key: String) -> String {
    LocalizationManager.shared.tr(key)
}

/// 带参数的界面文本快捷方式。
func L(_ key: String, _ args: CVarArg...) -> String {
    LocalizationManager.shared.tr(key, args)
}